events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    # ----- Dashboard custom -----
    upstream dashboard_up { server dashboard:8000; }

    # ----- Passbolt -----
    upstream passbolt_up { server passbolt:443; }


    # ----- Checkmk (UI corre en :5000) -----
    upstream checkmk_up { server checkmk:5000; }

    # Dashboard => http://<host>/
    server {
        listen 80 default_server;
        server_name _;

        location / {
            proxy_pass         http://dashboard_up;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }

    # Passbolt => https://passbolt.local
    server {
        listen 443 ssl;
        server_name passbolt.local;

        ssl_certificate     /etc/nginx/certs/passbolt.crt;
        ssl_certificate_key /etc/nginx/certs/passbolt.key;

        location / {
            proxy_pass         https://passbolt_up;
            proxy_ssl_verify   off;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto https;
        }
    }

    # Checkmk => http://checkmk.local/
    server {
        listen 80;
        server_name checkmk.local;

        location / {
            proxy_pass         http://checkmk_up;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }
}
